/** Default DSE watchlist symbols for seeding. */
export const SEED_TICKERS: Array<{ symbol: string; name?: string; sector?: string }> = [
  { symbol: 'GP', name: 'Grameenphone Ltd.', sector: 'Telecom' },
  { symbol: 'LHB', name: 'LafargeHolcim Bangladesh PLC', sector: 'Cement' },
  { symbol: 'SQURPHARMA', name: 'Square Pharmaceuticals Ltd.', sector: 'Pharma' },
  { symbol: 'BATBC', name: 'British American Tobacco Bangladesh', sector: 'Consumer' },
  { symbol: 'BRACBANK', name: 'BRAC Bank Ltd.', sector: 'Bank' },
  { symbol: 'CITYBANK', name: 'City Bank Ltd.', sector: 'Bank' },
  { symbol: 'ROBI', name: 'Robi Axiata Ltd.', sector: 'Telecom' },
  { symbol: 'RENATA', name: 'Renata Ltd.', sector: 'Pharma' },
  { symbol: 'OLYMPIC', name: 'Olympic Industries Ltd.', sector: 'Food' },
  { symbol: 'BERGERPBL', name: 'Berger Paints Bangladesh', sector: 'Industrial' },
  { symbol: 'MARICO', name: 'Marico Bangladesh Ltd.', sector: 'Consumer' },
  { symbol: 'UPGDCL', name: 'UPGDCL', sector: 'Power' },
  { symbol: 'POWERGRID', name: 'Power Grid Company', sector: 'Power' },
  { symbol: 'BSCCL', name: 'BSCCL', sector: 'Industrial' },
  { symbol: 'EBL', name: 'Eastern Bank Ltd.', sector: 'Bank' },
  { symbol: 'ACI', name: 'Advanced Chemical Industries', sector: 'Industrial' },
  { symbol: 'BEACONPHAR', name: 'Beacon Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'BXPHARMA', name: 'Beximco Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'CONFIDCEM', name: 'Confidence Cement', sector: 'Cement' },
  { symbol: 'HEIDELBCEM', name: 'Heidelberg Cement', sector: 'Cement' },
  { symbol: 'IBNSINA', name: 'Ibn Sina Pharmaceutical', sector: 'Pharma' },
  { symbol: 'IDLC', name: 'IDLC Finance Ltd.', sector: 'NBFI' },
  { symbol: 'IFIC', name: 'IFIC Bank Ltd.', sector: 'Bank' },
  { symbol: 'MTB', name: 'Mutual Trust Bank', sector: 'Bank' },
  { symbol: 'PRAGATILIF', name: 'Pragati Life Insurance', sector: 'Insurance' },
  { symbol: 'RECKITTBEN', name: 'Reckitt Benckiser', sector: 'Consumer' },
  { symbol: 'SQUARETEXT', name: 'Square Textiles', sector: 'Textile' },
  { symbol: 'UNILEVERCL', name: 'Unilever Consumer Care', sector: 'Consumer' },
  { symbol: 'WALTONHIL', name: 'Walton Hi-Tech Industries', sector: 'Industrial' },
];
